### ISSUE TITLE
March 2025 update 

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#1038]
```[tasklist]
### Tasks
- [ ] create a marker linking CH to AE https://github.com/Public-Health-Scotland/source-linkage-files/issues/1008
- [ ] Investigate 1819 processing https://github.com/Public-Health-Scotland/source-linkage-files/issues/997
- [ ] Update documentation. We can create flow charts to help visualise the process. This was particularly helpful for understanding the deaths processing due to the complexities.#1036
- [x] Time consumption documentation. How long does each function take to process? How long is the process for ep file start to finish? Same for individual file.#1037
- [x] Remove `slfhelper::get_chi()` #1035
- [ ] Check social care in targets #1034
- [x] Investigate `commhosp` flag #1030
- [x] Remove tests from targets #1031
- [ ] Check care home provider definitions #1028
- [ ] Automate homelessness completeness path #1024
- [ ] Check social care data from the platform #963
- [ ] Continue improving tests #929
- [x] bug - #1040
```

**Comment by Jennit07** [comment]
Zihao To do: 
- [ ] #1031
- [ ] #1035
