### ISSUE TITLE
Overall code review

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#215]
As discussed, we'll do a review of the code so far. Please edit this comment to add to/split/reorder the list of checks, once we have a list of checks we'll add our initials to each check and start doing PRs to fix any issues we find (if any).

## General

- [x] Check all relevant scripts are done - Setup, lookups and extract processing. **JT, JM** 
             - [ ] **(JT created spreadsheet with SPSS vs R code. We can update this as we go along)**
- [x] Check the open issues and assign, comment or close them as appropriate. - **ALL** **(checked 27/6 CH)**
- [x] Are there any files/scripts which shouldn't be there? e.g. old and unused/superseded code. **JT, JM**
- [x] Check that package requirements are up to date
- [x] Check we are regularly installing/updating the `createslf` package - may cause code to break when this was already working

### File path functions

- [ ] Do they all work in a consistent way.
- [ ] Do they use the same-named parameters and use `...` to pass unnamed parameters consistently. **JT**
- [ ] Are the names clear, consistent and unambiguous (and in 'snake_case'). **BM**
- [ ] Do they return a (valid) file path, which should be a `fs::path` object.

### All/Other functions

- [ ] Are the names clear and consistent (and in 'snake_case'). **BM**
- [ ] Are scripts organised well, e.g. are similar functions on the same script, or should some be split into their own scripts. **JT**
- [ ] Do they have sufficient tests. **ZL**
- [ ] Comments where appropriate.
- [x] #270 **CH**
  - [x] Clear, descriptive title.
  - [x] An `@description` tag with full description if appropriate.
  - [x] All parameters are clearly described.
  - [x] Return value is clearly described.
  - [x] Examples included, where appropriate e.g. for task type functions but not for SLF data specific functions.
  - [x] Links to other functions / packages where appropriate.
- [ ] Errors and warnings should use [`{cli}`](https://cli.r-lib.org/) in favour of `{rlang}` or base.

## Production scripts

- [ ] Does the code run without errors.
- [ ] Does the code produce the expected output. **BM (check output against 1920 activity files in sourcedev)**
- [ ] Read in the file specifying the types of variables. 
- [ ] All variables are in snake_case. **ZL**
- [ ] Do variables match those in the SPSS file. `names(<spss_produced_file>) == names(<r_produced_file>)`.
- [ ] Does the row count match the SPSS file. `nrow(<spss_produced_file>) == nrow(<r_produced_file>)`.
- [ ] No unnecessary code (especially sorting). **BM**
- [ ] Any common code which can be packaged into a function. **BM, ZL**
- [ ] Are necessary packages read in? any to be removed which are not being used? **ZL**
- [ ] Use `check_year_format` to wrap the year at the top for future use.
- [ ] Prefer using `<package>::<function>` instead of loading the package as this will make it simpler to convert the script to a function in the future.
- [ ] Liberal use of comments. **BM (Anything missing/not making sense?)**
- [ ] Are there tests? - If not create an issue and assign (check issues and PRs first) - **BM, ZL**
- [ ] Correct use of whitespace. **ZL** 
  - [ ] No empty line at the top of the script.  **ZL**
  - [ ] Empty line at the end. **ZL**
  - [ ] maximum 1 line between code blocks (if needed) **ZL**
  - [ ] 2 lines before sections **ZL**
- [ ] is the correct/relevant function being used for saving the output? 

## Documentation

- [ ] Is the documentation up to date? Any changes to functions above will need updating in the documentation  **linked to** #270 **CH** **up-to-date 27/6**
- [x] Is main-R up to date when we do a check? i.e. no notes, errors or warnings 
- [x] Does the roxygen documentation make sense? All parameters accounted for? **linked to** #270 **CH**
- [x] Is there enough info on the roxygen documentation on each script? anything to be added/removed?  **linked to** #270 **CH**
- [x] Are all family functions highlighted in the documentation?  **linked to** #270 **CH**
