### ISSUE TITLE
C01 - Create Episode file

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#332]
C01- Create Episode file conversion 

This script will add all datasets together to create the episode file. We will check CHI's are valid (use the PHSmethods package), drop the numeric date format and use date formats in R, do some tidying of the data and apply cij_pattypelogic to all records with a valid CHI number. Some of this script can be split out into others and I have made some issues for this which should cut down this script significantly. We should also be mindful about using functions for bits of code which are more complex in this script and split these out into new issues if this will be time-consuming.

Issues split out from this script: 
- [x] Remove maternity code (lines 98-101 and 165-170) and put it into `extract_maternity.R` (Issue #329)
- [x] Deal with SMRType: we can drop this and write this into each `extract_*.R` script (Issue #330)
- [x] Deal with PPA (Lines 212-362) Issue (#331)

**Comment by Jennit07** [comment]
This will eventually be a secondary level function called `run_ep_file` which will call upon various functions (e.g. add smrtype, add PPA etc). Example function below.

> run_ep_file <- function(processed_data_list, year) {
>   
>   slf_file <-
>   Bind data
>   dplyr::bind_rows(processed_data_list) %>%
>     
>      Check CHIs
>      Issue X / PR X
>     
>     ...
>     
>      Add PPAs
>     
>     ...
>   
> }

**Comment by shintoLamp** [comment]
See c01-create-episode-file/run_episode_file.R for skeleton code

**Comment by shintoLamp** [comment]
I think this issue can be closed as we have addressed everything Jen originally suggested and created a run of episode files.
