### ISSUE TITLE
Remaining Scripts to be converted into a function

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#500]
TO DO:

- [x] GP OOH (on hold #485)
- [x] GP OOH tests (#501)
- [x] ALL CH script (on hold #499)
- [x] sc demographics tests (PR open #496)
- [x] year specific care home extract (PR open #489)
- [x] LTC tests (PR open #497)
- [x] Alarms Telecare tests (PR open #498)
- [x] Home Care tests (PR open #503)
- [x] SDS tests (PR open #504)
- [x] DN tests (PR open #505)
- [x] All sc CH tests (PR open #507)
