### ISSUE TITLE
Issues with variables - July 2023

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#729]
@Jennit07 made a great comparison of variables between the existing and new files - [SLF variable list.xlsx](https://github.com/Public-Health-Scotland/source-linkage-files/files/12040950/SLF.variable.list.xlsx)

```[tasklist]
### Tasks
- [ ] Sort out the Postcode lookup / matching - variables with issues include `hbrescode` (HB2018), `datazone` and `hscp`
- [ ] Match the Social Care client variables to the individual file.
- [ ] Some code to do `anon_chi` - We could do this at the episode file and then just do swaps on the lookups before matching them in the individual file? Alternatively, we have code at the end like we used to, this is simpler but will be slower to run as it will involve reading and (re-)writing every file. 
- [ ] Delayed Discharges - Rename `dd_type` to `dd_quality`, and add `dd_responsible_lca` back in (this is in the original extract).
- [ ] `death_date` and `deceased` this is this file `get_slf_deaths_lookup_path(year)` and is created in `R/process_lookup_deaths.R`
- [ ] Variables to be removed, ideally at source (i.e. they don't get into `processed_data_list`). Episode - `hc_hours_derived`, `original_admission_date` (DD) `most_recent_gpprac` and `most_recent_postcode`. Individual - `cost_total_net_inc_dnas`.
```

**Comment by Jennit07** [comment]
Various PRs which have now been merged. This was all resolved for the June SLF update
