### ISSUE TITLE
 Add create_sending_location_test_flags to Social Care tests

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#818]
```[tasklist]
### Tests to add to
- [x] Client Lookup #783
- [x] Demographics Lookup
- [ ] All Care Home
- [x] Care Home yearly
- [ ] All Home Care
- [x] Home Care yearly
- [ ] All SDS
- [x] SDS yearly
- [ ] All A&T
- [x] A&T yearly
```

```[tasklist]
### Tasks
```
