### ISSUE TITLE
December Update TO DO

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#834]
For release
- [ ] Include social care data in 2023/24 file 
- [x] Investigate ICD10 codes for drug related admissions #836
- [x] Include the keep population flag #819 
- [ ] Deaths fixes #338 
- [x] Fix `ch_provider`  #858 
- [ ] Investigate and fix `sc_demographics` #855 
- [ ]  Fix issue with missing end dates in sc creating cases after death #848 
- [x] slfhelper::get_chi()
- [x] Request a new 2023/24 SPARRA extract

Internal changes:
- [x] Improve test workbooks #835 
- [ ] Fix issue with `read_slf_individual` reading in different years and different formats #860

**Comment by Jennit07** [comment]
To Do - pre update checks 20/11/23 
- [ ] MM - merge ch provider 
- [ ] MM- check latest sc id and make sure its in all social care 
- [ ] MM - Investigate demographic file with multiple chi per person 
- [ ] MM - check if happy with #849 
- [ ] JT - finish checking tests in #854 
- [ ] JT and MM - have a call in afternoon to check targets file and add #854 
- [ ] JT - check PR #852 
- [ ] JT - get boxi extracts 1pm with RV
- [ ] JT and MM - check over Keep population flag #847

**Comment by SwiftySalmon** [comment]
> * [ ]  MM - check if happy with [Make improvements to test workbooks #849](https://github.com/Public-Health-Scotland/source-linkage-files/pull/849) - mm this one needs the hscp2018 function added and then all good

**Comment by Jennit07** [comment]
Boxi extracts all downloaded and should be appearing in the temp file location. Need to clear out sourcedev before moving them to each year folder
