### ISSUE TITLE
Fix missing end dates for social care data

### ISSUE THREAD

**Issue by SwiftySalmon** [Public-Health-Scotland/source-linkage-files#848]
This is one of the scenarios uncovered in the death dates investigation. 

Some social care records have open end dates and our code sees that as ongoing activity. However, this is leading to cases where a patient has died but because there is no end date they continue to show up in the individual and episode files after death. 

Mark from the Social Care team added these notes on how they deal with this scenario: 

_"So when pulling in data from the equipment snapshot (or any other section) you add the variable "period_end_date". The missing end dates mean the episode is ongoing or was at the time it was submitted, so when an end date is missing it can be sent to the period end date for analysis. 
The methodology is slightly different since we do all our analyses by financial quarter/year, don't know if using dates more will affect that. 
When doing linked analysis we'll look within a 4-week period for death dates. If the service end date is within 4 weeks after the death date, the end date just gets set to the death date. If it's more than 4 weeks we exclude it from the analysis"_

```[tasklist]
### Tasks
- [ ] Add "period end date" to the social care data extraction scripts
- [ ] Set missing end dates to period end date
- [ ] Set service end date to death date IF service end date is within 4 weeks of death date, otherwise exclude.
- [ ] Check that patients are not showing up in individual file or episode file if the patient died in a previous financial year
- [ ] Potentially add tests to check?
```

**Comment by Jennit07** [comment]
complete in #852
