### ISSUE TITLE
March TO DO 

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#889]
- [x] Check DD underlying data #882 
- [ ] activity after deaths flag #862 
- [x] social care demographics investigations #758 
- [x] Update SC demographics and sds code
- [ ] data quality script for DM (ongoing work)
- [ ] investigate cup marker #776 #775 
- [x] ask geography team for parquet files (on hold) #820 
- [x] update the file layouts - compare the data vs file layout documentation #887
- [x] add codes to HL1 property type #121 
- [x] have a look at #508 
- [x] remove redundant code #603 
- [ ] check function #886 
- [x] check old file types (2014-2016) #860 
- [x] check function #850 
- [ ] Review moving files to hscdiip #888
- [x] Investigate adding `all LTCs` to slfhelper #902 
- [ ] Investigate adding 12 month HL1 flags #901 
- [x] Fix bug - NSUs showing psychiatry #908 
- [x] Fix bug - NAs showing in demographic cohort for `high_cc` #911

**Comment by Jennit07** [comment]
Ideas for including in the email from a user point of view: 
- [ ] Improvements to demographics and SDS #900 
- [ ] Delayed Discharges not matching onto admissions data #882 
- [ ] Fixed bug - NSUs showing pyschiatry #908 
- [ ] Fixed bug - NAs in demographic cohort #911
