### ISSUE TITLE
June TO DO

### ISSUE THREAD

**Issue by SwiftySalmon** [Public-Health-Scotland/source-linkage-files#932]
- [x] activity after deaths flag #862 #338 - **WIP**
- [ ] Test improvements 
- [x] #930 - **WIP**
- [ ]  #929
- [ ] #11
- [ ] #299
- [x] #938 
- [x] Homelessness  improvements  #928 #906  - **WIP**
- [ ] Care Home - review quarter function #915 
- [x] Care Home fill in ch names #553 
- [x] Care Home split episode counter #609 
- [x]  Permissions issues #920 
- [ ] data quality script for DM (ongoing work) - social care **WIP - Flexdashboard**
- [ ] Investigate CUP markers #775 #776 
- [ ] check all sc client variables pull through to episode file #106 
- [x] Check population files #941 - add to email update
- [x] #944 
- [x] anon_chi in each read in script
- [ ] Add additional documentation for SLFhelper and using the SLFs: https://github.com/Public-Health-Scotland/slfhelper/issues/78
- [x] Update News.md on GitHub
