### ISSUE TITLE
September 24 update

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#969]
- Run files 2017/18 onwards for any bug fixes and new care home methodology 
- Update Reference document - going forward, update this each quarter

Development
- [x] attach death dates to activity after death flag #961 
- [x] process deaths lookup needs added to targets #958 
- [x] automate process deaths lookup #957 #968 
- [x] Care home methodology review #915 #873
- [x]  client flags #106 
- [x] add cup markers  #775 #776 
- [x] New NSU cohort - 23/24 file #959 
- [x] get new sparra extract for 24/25 file #976 - email sent to team requesting for August completion
- [x] person_id missing from SDS #975  
- [x] person_id missing from client #714
- [x] investigate a new sc marker for a&e attendances #974 

Admin
- [x] Create new 24/25 files
- [x] Follow up with Homelessness team about completeness SG publication - how often do we update this? Update - I have asked the question and the team will look into this. I will then update our SOP to ensure we update this annually
- [x] Update documentation #887 
- [x] Run older files with updated R code #893 
- [x] decide if to remove IT deaths extract #338

**Comment by SwiftySalmon** [comment]
re: removing IT death extract #338 this is only used in care home code and I had a look and it would make no difference if we just used the boxi extract.
